# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - 'Task 8/**'
  pull_request:
    paths:
      - 'Task 8/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Start MongoDB service
      run: sudo service mongodb start

    - name: Wait for MongoDB to be ready
      run: |
        while ! nc -z localhost 27017; do
          sleep 1
        done

    - name: Build
      run: cd 'Task 8' && go build -v ./...

    - name: Test
      run: cd 'Task 8' && go test -v ./...
