# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - 'Task 8/**'
  pull_request:
    paths:
      - 'Task 8/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Install MongoDB
      run: |
        sudo apt-get update
        sudo apt-get install -y mongodb
        sudo systemctl start mongodb
        sudo systemctl status mongodb

    - name: Build
      run: cd 'Task 8' && go build -v ./...

    - name: Test
      run: cd 'Task 8' && go test -v ./...


    - name: Build
      run: cd 'Task 8' && go build -v ./...

    - name: Test
      run: cd 'Task 8' && go test -v ./...
