name: Go CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Install dependencies
        working-directory: Task 8
        run: |
          go mod download

      - name: Run Infrastructure Test
        working-directory: Task 8
        run: |
          go test -v ./Tests/infrastructure
      
      - name: Run Controller Test
        working-directory: Task 8
        run: |
          go test -v ./Tests/controllers
      
      - name: Run Usecase Test
        working-directory: Task 8
        run: |
          go test -v ./Tests/usecases

      - name: Build
        working-directory: Task 8
        run: |
          go build -v
