# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - 'Task 8/**'
  pull_request:
    paths:
      - 'Task 8/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: ./Task 8/go build -v ./...

    - name: Test
      run: ./Task 8/go test -v ./...
